/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVpsRouteImport } from './routes/_auth/vps'
import { Route as AuthTariffsRouteImport } from './routes/_auth/tariffs'
import { Route as AuthSyncJournalRouteImport } from './routes/_auth/sync-journal'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthResourcesRouteImport } from './routes/_auth/resources'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthRenewalsRouteImport } from './routes/_auth/renewals'
import { Route as AuthProvidersRouteImport } from './routes/_auth/providers'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthPaymentsRouteImport } from './routes/_auth/payments'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBalanceRouteImport } from './routes/_auth/balance'
import { Route as AuthAuditRouteImport } from './routes/_auth/audit'
import { Route as AuthAccountsRouteImport } from './routes/_auth/accounts'
import { Route as AuthVpsVpsIdRouteImport } from './routes/_auth/vps.$vpsId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVpsRoute = AuthVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTariffsRoute = AuthTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSyncJournalRoute = AuthSyncJournalRouteImport.update({
  id: '/sync-journal',
  path: '/sync-journal',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResourcesRoute = AuthResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRenewalsRoute = AuthRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProvidersRoute = AuthProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentsRoute = AuthPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBalanceRoute = AuthBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsRoute = AuthAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVpsVpsIdRoute = AuthVpsVpsIdRouteImport.update({
  id: '/$vpsId',
  path: '/$vpsId',
  getParentRoute: () => AuthVpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AuthAccountsRoute
  '/audit': typeof AuthAuditRoute
  '/balance': typeof AuthBalanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/payments': typeof AuthPaymentsRoute
  '/projects': typeof AuthProjectsRoute
  '/providers': typeof AuthProvidersRoute
  '/renewals': typeof AuthRenewalsRoute
  '/reports': typeof AuthReportsRoute
  '/resources': typeof AuthResourcesRoute
  '/settings': typeof AuthSettingsRoute
  '/sync-journal': typeof AuthSyncJournalRoute
  '/tariffs': typeof AuthTariffsRoute
  '/vps': typeof AuthVpsRouteWithChildren
  '/vps/$vpsId': typeof AuthVpsVpsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AuthAccountsRoute
  '/audit': typeof AuthAuditRoute
  '/balance': typeof AuthBalanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/payments': typeof AuthPaymentsRoute
  '/projects': typeof AuthProjectsRoute
  '/providers': typeof AuthProvidersRoute
  '/renewals': typeof AuthRenewalsRoute
  '/reports': typeof AuthReportsRoute
  '/resources': typeof AuthResourcesRoute
  '/settings': typeof AuthSettingsRoute
  '/sync-journal': typeof AuthSyncJournalRoute
  '/tariffs': typeof AuthTariffsRoute
  '/vps': typeof AuthVpsRouteWithChildren
  '/vps/$vpsId': typeof AuthVpsVpsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/accounts': typeof AuthAccountsRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/balance': typeof AuthBalanceRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/payments': typeof AuthPaymentsRoute
  '/_auth/projects': typeof AuthProjectsRoute
  '/_auth/providers': typeof AuthProvidersRoute
  '/_auth/renewals': typeof AuthRenewalsRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/resources': typeof AuthResourcesRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sync-journal': typeof AuthSyncJournalRoute
  '/_auth/tariffs': typeof AuthTariffsRoute
  '/_auth/vps': typeof AuthVpsRouteWithChildren
  '/_auth/vps/$vpsId': typeof AuthVpsVpsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/audit'
    | '/balance'
    | '/dashboard'
    | '/payments'
    | '/projects'
    | '/providers'
    | '/renewals'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/sync-journal'
    | '/tariffs'
    | '/vps'
    | '/vps/$vpsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/audit'
    | '/balance'
    | '/dashboard'
    | '/payments'
    | '/projects'
    | '/providers'
    | '/renewals'
    | '/reports'
    | '/resources'
    | '/settings'
    | '/sync-journal'
    | '/tariffs'
    | '/vps'
    | '/vps/$vpsId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/accounts'
    | '/_auth/audit'
    | '/_auth/balance'
    | '/_auth/dashboard'
    | '/_auth/payments'
    | '/_auth/projects'
    | '/_auth/providers'
    | '/_auth/renewals'
    | '/_auth/reports'
    | '/_auth/resources'
    | '/_auth/settings'
    | '/_auth/sync-journal'
    | '/_auth/tariffs'
    | '/_auth/vps'
    | '/_auth/vps/$vpsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vps': {
      id: '/_auth/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof AuthVpsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tariffs': {
      id: '/_auth/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof AuthTariffsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sync-journal': {
      id: '/_auth/sync-journal'
      path: '/sync-journal'
      fullPath: '/sync-journal'
      preLoaderRoute: typeof AuthSyncJournalRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resources': {
      id: '/_auth/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthResourcesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/renewals': {
      id: '/_auth/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthRenewalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/providers': {
      id: '/_auth/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthProvidersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payments': {
      id: '/_auth/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthPaymentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/balance': {
      id: '/_auth/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthBalanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vps/$vpsId': {
      id: '/_auth/vps/$vpsId'
      path: '/$vpsId'
      fullPath: '/vps/$vpsId'
      preLoaderRoute: typeof AuthVpsVpsIdRouteImport
      parentRoute: typeof AuthVpsRoute
    }
  }
}

interface AuthVpsRouteChildren {
  AuthVpsVpsIdRoute: typeof AuthVpsVpsIdRoute
}

const AuthVpsRouteChildren: AuthVpsRouteChildren = {
  AuthVpsVpsIdRoute: AuthVpsVpsIdRoute,
}

const AuthVpsRouteWithChildren =
  AuthVpsRoute._addFileChildren(AuthVpsRouteChildren)

interface AuthRouteChildren {
  AuthAccountsRoute: typeof AuthAccountsRoute
  AuthAuditRoute: typeof AuthAuditRoute
  AuthBalanceRoute: typeof AuthBalanceRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPaymentsRoute: typeof AuthPaymentsRoute
  AuthProjectsRoute: typeof AuthProjectsRoute
  AuthProvidersRoute: typeof AuthProvidersRoute
  AuthRenewalsRoute: typeof AuthRenewalsRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthResourcesRoute: typeof AuthResourcesRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSyncJournalRoute: typeof AuthSyncJournalRoute
  AuthTariffsRoute: typeof AuthTariffsRoute
  AuthVpsRoute: typeof AuthVpsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountsRoute: AuthAccountsRoute,
  AuthAuditRoute: AuthAuditRoute,
  AuthBalanceRoute: AuthBalanceRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPaymentsRoute: AuthPaymentsRoute,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthProvidersRoute: AuthProvidersRoute,
  AuthRenewalsRoute: AuthRenewalsRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthResourcesRoute: AuthResourcesRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSyncJournalRoute: AuthSyncJournalRoute,
  AuthTariffsRoute: AuthTariffsRoute,
  AuthVpsRoute: AuthVpsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
